# Generated by Django 4.2 on 2026-04-08 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('SCAN', 'Scan'), ('SUBMIT_SESSION', 'Submit Session'), ('ASSIGN', 'Assign'), ('GRADE', 'Grade'), ('EDIT_MARKS', 'Edit Marks'), ('FLAG', 'Flag'), ('AMENDMENT_REQUEST', 'Amendment Request'), ('AMENDMENT_COMPLETE', 'Amendment Complete'), ('RESULT_GENERATED', 'Result Generated')], max_length=30)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
