# Generated by Django 4.2 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('SCAN', 'Scan'), ('SUBMIT_SESSION', 'Submit Session'), ('ASSIGN', 'Assign'), ('GRADE', 'Grade'), ('EDIT_MARKS', 'Edit Marks'), ('FLAG', 'Flag'), ('AMENDMENT_REQUEST', 'Amendment Request'), ('AMENDMENT_COMPLETE', 'Amendment Complete'), ('AMEND_MARKS', 'Amend Marks'), ('RESULT_GENERATED', 'Result Generated')], max_length=30),
        ),
    ]
