# Generated by Django 4.2 on 2026-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('SCAN', 'Scan'), ('SUBMIT_SESSION', 'Submit Session'), ('ASSIGN', 'Assign'), ('GRADE', 'Grade'), ('EDIT_MARKS', 'Edit Marks'), ('FLAG', 'Flag'), ('AMENDMENT_REQUEST', 'Amendment Request'), ('AMENDMENT_COMPLETE', 'Amendment Complete'), ('AMEND_MARKS', 'Amend Marks'), ('RESULT_GENERATED', 'Result Generated'), ('BUNDLE_ASSIGNED', 'Bundle Assigned'), ('MOD_SAMPLE_GEN', 'Moderation Sample Generated'), ('MOD_REQUESTED', 'Moderation Requested'), ('MOD_COMP_PASSED', 'Moderation Comparison Passed'), ('MOD_COMP_FAILED', 'Moderation Comparison Failed'), ('MOD_CORRECTION', 'Moderation Correction'), ('MOD_UNLOCKED', 'Moderation Unlocked'), ('CRIT_TRIGGERED', 'Critical Assessment Triggered'), ('CRIT_VERIFIED', 'Critical Verified'), ('CRIT_COMPARISON', 'Critical Comparison'), ('CRIT_CORRECTED', 'Critical Corrected')], max_length=30),
        ),
    ]
