# Generated by Django 4.2 on 2026-04-08 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('semester', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField()),
                ('sections', models.JSONField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_scheme', to='scanning.subject')),
            ],
            options={
                'db_table': 'marking_schemes',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_number', models.CharField(max_length=100)),
                ('total_sheets', models.PositiveIntegerField()),
                ('qr_raw_data', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bundles', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='scanning.subject')),
            ],
            options={
                'db_table': 'bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='scanned_images/')),
                ('page_number', models.PositiveIntegerField()),
                ('is_first_page', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scanning.bundle')),
            ],
            options={
                'db_table': 'answer_sheet_images',
                'ordering': ['roll_number', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='answer_sheets/')),
                ('pdf_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('under_evaluation', 'Under Evaluation'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('last_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.CharField(blank=True, choices=[('Blurry', 'Blurry'), ('Malpractice', 'Malpractice'), ('Missing Pages', 'Missing Pages'), ('Other', 'Other')], max_length=50, null=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sheets', to=settings.AUTH_USER_MODEL)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='scanning.bundle')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_sheets',
                'ordering': ['roll_number'],
                'unique_together': {('bundle', 'roll_number')},
            },
        ),
    ]
