# Generated by Django 4.2 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='qr_raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
