# Generated by Django 4.2.7 on 2026-04-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_alter_bundle_qr_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='academic_year',
            field=models.CharField(default='2025-26', help_text='e.g. 2025-26', max_length=20),
        ),
    ]
