# Generated by Django 4.2 on 2026-04-20 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanning', '0003_bundle_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersheet',
            options={'ordering': ['token']},
        ),
        migrations.AlterModelOptions(
            name='answersheetimage',
            options={'ordering': ['token', 'page_number']},
        ),
        migrations.AlterUniqueTogether(
            name='answersheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='answersheetimage',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True)),
                ('roll_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_tokens', to='scanning.subject')),
            ],
            options={
                'db_table': 'student_tokens',
                'unique_together': {('roll_number', 'subject')},
            },
        ),
    ]
