# Generated by Django 4.2 on 2026-04-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0005_backfill_tokens'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answersheet',
            unique_together={('bundle', 'token')},
        ),
    ]
