# Generated by Django 4.2 on 2026-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0006_add_token_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Lowest Laplacian variance score across pages', null=True),
        ),
    ]
